In [1]:
import numpy as np

A = np.array([
    [0, 1, 1, 1, 3],
    [1, 0, 0, 1, 0],
    [0, 1, 1, 5, 2],
    [2, 0, 0, 1, 2]
])

B = np.array([
    [1, 1, 2, 2, 2],
    [1, 2, 0, 0, 1],
    [1, 4, 2, 1, 2],
    [2, 2, 2, 2, 2]
])

C = np.array([
    [1, 0, 5, 0, 1],
    [1, 1, 1, 1, 3],
    [1, 3, 0, 2, 7],
    [3, 0, 5, 3, 2]
])

D = np.array([
    [3, 1, 5, 0, 1],
    [0, 3, 7, 7, 0],
    [5, 0, 0, 3, 5],
    [3, 5, 3, 2, 0]
])

E = np.array([
    [1, 0, 0, 0, 0],
    [0, 10, 0, 15, 0],
    [0, 5, 0, 15, 5],
    [0, 0, 2, 5, 0]
])

def vung_an_toan(tong_nguy_co):
    return tong_nguy_co <= 5

tong_nguy_co_a = E
an_toan_a = vung_an_toan(tong_nguy_co_a)

tong_nguy_co_b = A + B + C
an_toan_b = vung_an_toan(tong_nguy_co_b)

tong_nguy_co_c = A + D
an_toan_c = vung_an_toan(tong_nguy_co_c)

tong_nguy_co_d = B + C + D
an_toan_d = vung_an_toan(tong_nguy_co_d)

tong_nguy_co_e = A + B + C + D + E
an_toan_e = vung_an_toan(tong_nguy_co_e)

def in_ket_qua(tieude, matrix_bool):
    print(f"\n{tieude}")
    print(matrix_bool.astype(int))  

in_ket_qua("a) An toàn chiến dịch ngắn hạn (chỉ lộ bí mật):", an_toan_a)
in_ket_qua("b) An toàn tập luyện thời bình (không lộ bí mật, không bệnh dịch):", an_toan_b)
in_ket_qua("c) An toàn theo mùa khô (chỉ cháy rừng và bệnh dịch):", an_toan_c)
in_ket_qua("d) An toàn trong mùa mưa (lũ, sạt lở, bệnh dịch):", an_toan_d)
in_ket_qua("e) An toàn trong 8 tháng (tất cả yếu tố):", an_toan_e)



a) An toàn chiến dịch ngắn hạn (chỉ lộ bí mật):
[[1 1 1 1 1]
 [1 0 1 0 1]
 [1 1 1 0 1]
 [1 1 1 1 1]]

b) An toàn tập luyện thời bình (không lộ bí mật, không bệnh dịch):
[[1 1 0 1 0]
 [1 1 1 1 1]
 [1 0 1 0 0]
 [0 1 0 0 0]]

c) An toàn theo mùa khô (chỉ cháy rừng và bệnh dịch):
[[1 1 0 1 1]
 [1 1 0 0 1]
 [1 1 1 0 0]
 [1 1 1 1 1]]

d) An toàn trong mùa mưa (lũ, sạt lở, bệnh dịch):
[[1 1 0 1 1]
 [1 0 0 0 1]
 [0 0 1 0 0]
 [0 0 0 0 1]]

e) An toàn trong 8 tháng (tất cả yếu tố):
[[0 1 0 1 0]
 [1 0 0 0 1]
 [0 0 1 0 0]
 [0 0 0 0 0]]
