In [1]:
from scipy import linalg
import numpy as np

a = np.array([1, 2, 3])
b = np.array([(1+9j, 2j, 3j), (4j, 5j, 6j)]) 
c = np.array([[(0.5, 1.5, 10), (3, 2, 1)], [(6, 5, 4), (7, 8, 9)]])  

A = np.matrix(np.random.random((2, 2))) 
B = np.asmatrix(b)  
C = np.mat(np.random.random((10, 5))) 
D = np.mat([[4, 3], [2, 6]])  

print("Ma trận F = np.eye(3, k=1):")
F = np.eye(3, k=1)
print(F)

print("\nMa trận F = np.eye(3, k=0):")
F0 = np.eye(3, k=0)
print(F0)

print("\nMa trận F = np.eye(3, k=-1):")
F_1 = np.eye(3, k=-1)
print(F_1)

rank_C = np.linalg.matrix_rank(C)
print("\nHạng ma trận C:", rank_C)

print("\nMa trận A:")
print(A)
print("\nMa trận nghịch đảo của A (A.I):")
print(A.I)

print("\nMa trận nghịch đảo của A (scipy.linalg.inv):")
A_inv = linalg.inv(A)
print(A_inv)

det_A = linalg.det(A)
print("\nĐịnh thức của ma trận A:", det_A)

print("\nChuyển vị của A (A.T):")
print(A.T)

print("\nChuyển vị liên hợp của A (A.H):")
print(A.H)

b_vec = np.array([1, 2])
sol = linalg.solve(A, b_vec)
print("\nNghiệm của hệ A*x = b_vec:")
print(sol)

E = np.mat(a).T
print("\nMa trận cột E từ vector a:")
print(E)

print("\nGiải bài toán bình phương tối thiểu F*x ≈ E:")
res = linalg.lstsq(F0, E)
print("Nghiệm:")
print(res[0])
print("Residuals:")
print(res[1])

print("\nCộng ma trận A + D:")
print(np.add(A, D))

print("\nTrừ ma trận A - D:")
print(np.subtract(A, D))

print("\nChia ma trận A / D (phần tử):")
print(np.divide(A, D))

print("\nNhân ma trận A @ D:")
print(A @ D)

print("\nNhân từng phần tử D * A:")
print(np.multiply(D, A))

print("\nNhân ma trận np.dot(A, D):")
print(np.dot(A, D))

print("\nTích vô hướng np.vdot(A, D):")
print(np.vdot(A, D))

print("\nHàm lũy thừa expm(A):")
print(linalg.expm(A))

print("\nHàm logarithm logm(A):")
print(linalg.logm(A))


Ma trận F = np.eye(3, k=1):
[[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]

Ma trận F = np.eye(3, k=0):
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Ma trận F = np.eye(3, k=-1):
[[0. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]]

Hạng ma trận C: 5

Ma trận A:
[[0.8501364  0.12507974]
 [0.71081146 0.79315768]]

Ma trận nghịch đảo của A (A.I):
[[ 1.35493546 -0.21367123]
 [-1.21426505  1.45227107]]

Ma trận nghịch đảo của A (scipy.linalg.inv):
[[ 1.35493546 -0.21367123]
 [-1.21426505  1.45227107]]

Định thức của ma trận A: 0.5853841036319299

Chuyển vị của A (A.T):
[[0.8501364  0.71081146]
 [0.12507974 0.79315768]]

Chuyển vị liên hợp của A (A.H):
[[0.8501364  0.71081146]
 [0.12507974 0.79315768]]

Nghiệm của hệ A*x = b_vec:
[0.92759301 1.69027709]

Ma trận cột E từ vector a:
[[1]
 [2]
 [3]]

Giải bài toán bình phương tối thiểu F*x ≈ E:
Nghiệm:
[[1.]
 [2.]
 [3.]]
Residuals:
[]

Cộng ma trận A + D:
[[4.8501364  3.12507974]
 [2.71081146 6.79315768]]

Trừ ma trận A - D:
[[-3.1498636  -2.87492026]
 [-1.28918854 -5.20684232