In [1]:
import numpy as np

# Ma trận phân kỳ A
print("Ma trận A:")
A = np.array([[0, 1], [1, 0]])
print(A)

temp = A.dot(A)
print("\nA^2:")
print(temp)

k = 6
print("\nLũy thừa A^k từ k=3 đến k=6:")
for i in range(k - 2):
    temp = temp.dot(A)
    print(temp)
    print('---')
    
print("Nhận xét: Ma trận A lặp đi lặp lại các giá trị do A^2 = I (ma trận đơn vị).")

# Ma trận phân kỳ B
print("\nMa trận B:")
B = np.array([[0, -1], [-1, 0]])
print(B)

temp = B.dot(B)
print("\nB^2:")
print(temp)

k = 5
print("\nLũy thừa B^k từ k=3 đến k=5:")
for i in range(k - 2):
    temp = temp.dot(B)
    print(temp)
    print('---')

print("Nhận xét: Ma trận B cũng phân kỳ, luỹ thừa lặp lại các giá trị như A.")

# Ma trận hội tụ C
print("\nMa trận C:")
C = np.array([[1, 0, 0], [0, 0.5, 1], [0, 0, 0.5]])
print(C)

temp = C.dot(C)
print("\nC^2:")
print(temp)

k = 1000
for i in range(k - 1):
    temp = temp.dot(C)

print(f"\nC^{k}:")
print(temp)
print("Nhận xét: Ma trận hội tụ nên C^k tiến tới một ma trận cố định khi k → ∞.")

# Tính tiếp 1000 lần tích nữa
for i in range(k - 1):
    temp = temp.dot(C)

print(f"\nC^{2*k}:")
print(temp)
print("Nhận xét: Ma trận hội tụ nên kết quả không đổi khi tính thêm lũy thừa lớn nữa.")


Ma trận A:
[[0 1]
 [1 0]]

A^2:
[[1 0]
 [0 1]]

Lũy thừa A^k từ k=3 đến k=6:
[[0 1]
 [1 0]]
---
[[1 0]
 [0 1]]
---
[[0 1]
 [1 0]]
---
[[1 0]
 [0 1]]
---
Nhận xét: Ma trận A lặp đi lặp lại các giá trị do A^2 = I (ma trận đơn vị).

Ma trận B:
[[ 0 -1]
 [-1  0]]

B^2:
[[1 0]
 [0 1]]

Lũy thừa B^k từ k=3 đến k=5:
[[ 0 -1]
 [-1  0]]
---
[[1 0]
 [0 1]]
---
[[ 0 -1]
 [-1  0]]
---
Nhận xét: Ma trận B cũng phân kỳ, luỹ thừa lặp lại các giá trị như A.

Ma trận C:
[[1.  0.  0. ]
 [0.  0.5 1. ]
 [0.  0.  0.5]]

C^2:
[[1.   0.   0.  ]
 [0.   0.25 1.  ]
 [0.   0.   0.25]]

C^1000:
[[1.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 4.66631809e-302 9.34196882e-299]
 [0.00000000e+000 0.00000000e+000 4.66631809e-302]]
Nhận xét: Ma trận hội tụ nên C^k tiến tới một ma trận cố định khi k → ∞.

C^2000:
[[1. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Nhận xét: Ma trận hội tụ nên kết quả không đổi khi tính thêm lũy thừa lớn nữa.
