In [1]:
import numpy as np
from scipy import linalg
import sympy as sp

D = np.mat([[3,4], [5,6]])
print("Ma trận D:")
print(D)
print()

C = np.mat(np.random.random((5,7)))
print("Ma trận ngẫu nhiên C (5x7):")
print(C)
print()

A = np.mat(np.random.random((2,2)))
print("Ma trận ngẫu nhiên A (2x2):")
print(A)
print()

b = np.array([(1+5j, 2j, 3j), (4, 5, 6)])
B = np.asmatrix(b)
print("Vector b:")
print(b)
print("Vector b dưới dạng ma trận B:")
print(B)
print()

print("Chuyển vị ma trận A.T:")
print(A.T)
print()

print("Ma trận nghịch đảo A.I:")
print(A.I)
print()

print("Ma trận nghịch đảo bằng scipy.linalg.inv:")
print(linalg.inv(A))
print()

M = np.array([[-1,3,2],[0,-2,1],[1,5,-2]])
print("Ma trận M:")
print(M)
print()

M_lower = np.tril(M)
print("Ma trận tam giác dưới của M:")
print(M_lower)
print()

M_upper = np.triu(M)
print("Ma trận tam giác trên của M:")
print(M_upper)
print()

v_diag = np.diag(M)
print("Vector đường chéo của M:")
print(v_diag)
print()

M_diag = np.diag(v_diag)
print("Ma trận đường chéo tạo từ vector trên:")
print(M_diag)
print()

I2 = np.identity(2)
print("Ma trận đơn vị 2x2:")
print(I2)
print()

x, y, z = sp.symbols('x y z')

eq1 = sp.Eq(2*x + 3, 2)
eq2 = sp.Eq(0, 3*y + 4)
eq3 = sp.Eq(1, z)

solution = sp.solve([eq1, eq2, eq3], (x, y, z))
print("Nghiệm của hệ phương trình (x, y, z):")
print(solution)
print()

a1 = np.array([[1,2],[3,4]])
a2 = np.array([[1,2],[3,4]])
a3 = np.array([[1,2],[3,4.0000001]])

print("a1 và a2 bằng nhau tuyệt đối:", np.array_equal(a1, a2))
print("a1 và a3 bằng nhau tuyệt đối:", np.array_equal(a1, a3))
print("a1 và a3 gần bằng nhau (allclose):", np.allclose(a1, a3))
print("a1 và a3 tương đương (array_equiv):", np.array_equiv(a1, a3))


Ma trận D:
[[3 4]
 [5 6]]

Ma trận ngẫu nhiên C (5x7):
[[0.158978   0.18764938 0.31532788 0.29794804 0.8347866  0.53687536
  0.21511721]
 [0.1494625  0.57072463 0.12940494 0.55971971 0.73969126 0.114601
  0.09950541]
 [0.51286497 0.67622656 0.482037   0.86046148 0.9395046  0.35211168
  0.02652002]
 [0.07782542 0.69829626 0.01358816 0.56889076 0.79675663 0.67165526
  0.67597643]
 [0.42211472 0.37713178 0.68509786 0.31001017 0.16564844 0.77254848
  0.15079727]]

Ma trận ngẫu nhiên A (2x2):
[[0.04929647 0.73527478]
 [0.35377879 0.47061203]]

Vector b:
[[1.+5.j 0.+2.j 0.+3.j]
 [4.+0.j 5.+0.j 6.+0.j]]
Vector b dưới dạng ma trận B:
[[1.+5.j 0.+2.j 0.+3.j]
 [4.+0.j 5.+0.j 6.+0.j]]

Chuyển vị ma trận A.T:
[[0.04929647 0.35377879]
 [0.73527478 0.47061203]]

Ma trận nghịch đảo A.I:
[[-1.98633247  3.10340591]
 [ 1.49320935 -0.20806773]]

Ma trận nghịch đảo bằng scipy.linalg.inv:
[[-1.98633247  3.10340591]
 [ 1.49320935 -0.20806773]]

Ma trận M:
[[-1  3  2]
 [ 0 -2  1]
 [ 1  5 -2]]

Ma trận tam gi