In [1]:
import numpy as np

A = np.reshape(np.arange(36.0), (6,6))
print("Ma trận A (6x6):")
print(A)
print()

I6 = np.identity(6)
print("Ma trận đơn vị I6 (6x6):")
print(I6)
print()

print("Số phần tử của ma trận A:", A.size)
print()

print("Đường chéo của ma trận A:")
print(np.diagonal(A))
print()

A = A + I6
print("Ma trận A sau khi cộng ma trận đơn vị I6:")
print(A)
print()

vecB = np.array([1., 2., 3., 4., 5., 6.])
print("Vector vecB:")
print(vecB)
print()

C = A.dot(vecB)
print("Tích ma trận A x vector vecB:")
print(C)
print()

D = np.array([
    [1., 2., 3., 4., 5., 6.],
    [1., 0., 1., 0., 1., 0.]
])
print("Ma trận D (2x6):")
print(D)
print()

F = np.array([
    [1., 1.],
    [2., 0.],
    [3., 1.],
    [4., 0.],
    [5., 1.],
    [6., 0.]
])
print("Ma trận F (6x2):")
print(F)
print()

G = A.dot(F)
print("Tích ma trận A x F:")
print(G)
print()

try:
    A_inv = np.linalg.inv(A)
    print("Ma trận nghịch đảo của A:")
    print(A_inv)
except np.linalg.LinAlgError:
    print("Ma trận A không khả nghịch (không tồn tại ma trận nghịch đảo)")
print()

print("Tính np.linalg.inv(np.linalg.inv(A)) (nếu A khả nghịch):")
try:
    double_inv = np.linalg.inv(np.linalg.inv(A))
    print("Kết quả:")
    print(double_inv)
    print("Giá trị này phải bằng ma trận A gốc vì nghịch đảo của nghịch đảo ma trận là chính ma trận đó.")
except np.linalg.LinAlgError:
    print("Không thể tính vì A hoặc nghịch đảo của A không khả nghịch.")
print()


Ma trận A (6x6):
[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. 11.]
 [12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21. 22. 23.]
 [24. 25. 26. 27. 28. 29.]
 [30. 31. 32. 33. 34. 35.]]

Ma trận đơn vị I6 (6x6):
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]

Số phần tử của ma trận A: 36

Đường chéo của ma trận A:
[ 0.  7. 14. 21. 28. 35.]

Ma trận A sau khi cộng ma trận đơn vị I6:
[[ 1.  1.  2.  3.  4.  5.]
 [ 6.  8.  8.  9. 10. 11.]
 [12. 13. 15. 15. 16. 17.]
 [18. 19. 20. 22. 22. 23.]
 [24. 25. 26. 27. 29. 29.]
 [30. 31. 32. 33. 34. 36.]]

Vector vecB:
[1. 2. 3. 4. 5. 6.]

Tích ma trận A x vector vecB:
[ 71. 198. 325. 452. 579. 706.]

Ma trận D (2x6):
[[1. 2. 3. 4. 5. 6.]
 [1. 0. 1. 0. 1. 0.]]

Ma trận F (6x2):
[[1. 1.]
 [2. 0.]
 [3. 1.]
 [4. 0.]
 [5. 1.]
 [6. 0.]]

Tích ma trận A x F:
[[ 71.   7.]
 [198.  24.]
 [325.  43.]
 [452.  60.]
 [579.  79.]
 [706.  96.]]

Ma trận nghịch đảo của A:
[[ 0.37022901 -0.456