In [1]:
import numpy as np
from numpy.linalg import inv, matrix_power

A = np.array([[2, 3],
              [3, -6]])

D = np.array([[-7, 0],
              [0, 3]])

P = np.array([[-1.0/3, 3],
              [1, 1]])

P_inv = inv(P)
print("Ma trận P⁻¹ là:")
print(np.round(P_inv, 4)) 

print("\nA · P =")
print(np.round(A @ P, 4))

print("\nP · D =")
print(np.round(P @ D, 4))


D_pow = matrix_power(D, 1000)

A_pow = P @ D_pow @ P_inv
print("\nA^1000 tính bằng chéo hóa là:")
print(np.round(A_pow, 4))  

print("\nMa trận D^2 là:")
print(D @ D)



Ma trận P⁻¹ là:
[[-0.3  0.9]
 [ 0.3  0.1]]

A · P =
[[ 2.3333  9.    ]
 [-7.      3.    ]]

P · D =
[[ 2.3333  9.    ]
 [-7.      3.    ]]

A^1000 tính bằng chéo hóa là:
[[-6.25396533e+08 -3.52488701e+08]
 [-3.52488701e+08  3.14573335e+08]]

Ma trận D^2 là:
[[49  0]
 [ 0  9]]
