In [1]:
import numpy as np
from numpy import linalg as LA

A = np.matrix([[1, 0],
               [0, 0]])

B = np.matrix([[0, 0],
               [0, 1]])

print("Ma trận A:")
print(A)
print("\nMa trận B:")
print(B)

print("\nThử lấy nghịch đảo ma trận A:")
try:
    inv_A = LA.inv(A)
    print(inv_A)
except LA.LinAlgError as e:
    print("Lỗi:", e)

print("\nThử lấy nghịch đảo ma trận B:")
try:
    inv_B = LA.inv(B)
    print(inv_B)
except LA.LinAlgError as e:
    print("Lỗi:", e)

print("\nThử lấy nghịch đảo ma trận A + B:")
try:
    inv_sum = LA.inv(A + B)
    print(inv_sum)
except LA.LinAlgError as e:
    print("Lỗi:", e)

det_A = LA.det(A)
det_B = LA.det(B)
det_sum = LA.det(A + B)

print(f"\nĐịnh thức của A: {det_A}")
print(f"Định thức của B: {det_B}")
print(f"Định thức của A + B: {det_sum}")


Ma trận A:
[[1 0]
 [0 0]]

Ma trận B:
[[0 0]
 [0 1]]

Thử lấy nghịch đảo ma trận A:
Lỗi: Singular matrix

Thử lấy nghịch đảo ma trận B:
Lỗi: Singular matrix

Thử lấy nghịch đảo ma trận A + B:
[[1. 0.]
 [0. 1.]]

Định thức của A: 0.0
Định thức của B: 0.0
Định thức của A + B: 1.0
