In [1]:
import numpy as np

# Khai báo vector và ma trận
A = np.array([3, -2, 1, 4])
B = np.array([-1, 5, 0, 2])
C = np.array([[2, -1, 3],
              [1, 4, -2],
              [0, 2, 5]])

# Câu 1a: Tính A + B và 2A + 3B
sum_AB = A + B
expr = 2 * A + 3 * B

print("Câu 1a:")
print("A + B =", sum_AB)
print("2A + 3B =", expr)

# Câu 1b: Tích vô hướng A · B và góc giữa hai vector (độ)
dot_product = np.dot(A, B)
norm_A = np.linalg.norm(A)
norm_B = np.linalg.norm(B)
cos_theta = dot_product / (norm_A * norm_B)
theta_rad = np.arccos(cos_theta)
theta_deg = np.degrees(theta_rad)

print("\nCâu 1b:")
print("Tích vô hướng A · B =", dot_product)
print(f"Góc giữa A và B = {theta_deg:.3f} độ")

# Câu 1c: Tính tích ma trận C × C^T
C_transpose = C.T
product_C = np.dot(C, C_transpose)

print("\nCâu 1c:")
print("Ma trận C × C^T =\n", product_C)


Câu 1a:
A + B = [2 3 1 6]
2A + 3B = [ 3 11  2 14]

Câu 1b:
Tích vô hướng A · B = -5
Góc giữa A và B = 99.594 độ

Câu 1c:
Ma trận C × C^T =
 [[14 -8 13]
 [-8 21 -2]
 [13 -2 29]]
