In [1]:
import numpy as np

def minor(A, i, j):
    """Trả về định thức ma trận con bằng cách loại bỏ hàng i và cột j."""
    minor_matrix = np.delete(np.delete(A, i, axis=0), j, axis=1)
    return np.linalg.det(minor_matrix)

def cofactor_matrix(A):
    """Tính ma trận hệ số kép (cofactor matrix)."""
    n = A.shape[0]
    C = np.zeros_like(A, dtype=float)
    for i in range(n):
        for j in range(n):
            C[i, j] = ((-1) ** (i + j)) * minor(A, i, j)
    return C

def adjoint_matrix(A):
    """Tính ma trận liên hợp (adjoint matrix)."""
    C = cofactor_matrix(A)
    return C.T

if __name__ == "__main__":
    A = np.array([[1, 2, 3],
                  [0, 4, 5],
                  [1, 0, 6]])
    
    print("Ma trận A:")
    print(A)
    
    C = cofactor_matrix(A)
    print("\nMa trận hệ số kép (cofactor matrix):")
    print(C)
    
    adj = adjoint_matrix(A)
    print("\nMa trận liên hợp (adjoint matrix):")
    print(adj)


Ma trận A:
[[1 2 3]
 [0 4 5]
 [1 0 6]]

Ma trận hệ số kép (cofactor matrix):
[[ 24.   5.  -4.]
 [-12.   3.   2.]
 [ -2.  -5.   4.]]

Ma trận liên hợp (adjoint matrix):
[[ 24. -12.  -2.]
 [  5.   3.  -5.]
 [ -4.   2.   4.]]
