In [1]:
import numpy as np
from itertools import permutations

def sgn_by_def(sigma):
    """
    Tính dấu (sign) của một hoán vị sigma.
    sigma là tuple hoặc list chứa các số 0-based.
    """
    inv_count = 0
    n = len(sigma)
    for i in range(n):
        for j in range(i+1, n):
            if sigma[i] > sigma[j]:
                inv_count += 1
    return 1 if inv_count % 2 == 0 else -1

def det_by_definition(A):
    """
    Tính định thức của ma trận vuông A theo định nghĩa:
    det(A) = sum_{sigma in S_n} sgn(sigma) * product_{i=1 to n} A[i, sigma[i]]
    """
    n = A.shape[0]
    assert A.shape[0] == A.shape[1], "Ma trận phải là vuông"
    
    det_val = 0
    for sigma in permutations(range(n)):
        sgn = sgn_by_def(sigma)
        prod = 1
        for i in range(n):
            prod *= A[i, sigma[i]]
        det_val += sgn * prod
    return det_val

if __name__ == "__main__":
    A = np.array([
        [3, 5, -8],
        [4, 12, -1],
        [2, 5, 3]
    ])
    
    det_calc = det_by_definition(A)
    det_numpy = np.linalg.det(A)
    
    print("Ma trận A:")
    print(A)
    print("\nĐịnh thức tính theo định nghĩa:", det_calc)
    print("Định thức tính theo numpy.linalg.det:", det_numpy)


Ma trận A:
[[ 3  5 -8]
 [ 4 12 -1]
 [ 2  5  3]]

Định thức tính theo định nghĩa: 85
Định thức tính theo numpy.linalg.det: 85.00000000000001
